services:
  - type: web
    name: quality-dashboard-demo
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: JIRA_BASE_URL
        value: https://atharvporwal051.atlassian.net
      - key: JIRA_EMAIL
        sync: false
      - key: JIRA_API_TOKEN
        sync: false
      - key: JIRA_PROJECT_KEY
        value: DD
      - key: JIRA_SPACE_KEYS
        value: DD
      - key: ZEPHYR_API_BASE_URL
        value: https://eu.api.zephyrscale.smartbear.com/v2
      - key: ZEPHYR_API_TOKEN
        sync: false
